<div class="column">
    <form action="index.php?route=8" method="POST">
        <h2>Créer un nouvel article</h2>
        <div class="row">
            <label for="title">Titre</label>
            <input type="text" id="title" name="title" required autofocus>
        </div>
        <div class="row">
            <label for="content">Contenu</label>
            <textarea type="text" id="content" name="content"></textarea>
        </div>
        <button type="submit" class="button">Publier l'article</button>
    </form>
</div>