<div class="row">
    <div class="column">
        <form action="index.php?route=4" method ="POST">
            <h2>Connexion</h2>
            <div class="pseudo">
                <label for="pseudo">Pseudo : </label>
                <input type="text" id="pseudo" name="pseudo" required>
            </div>
            <div class="password">
                <label for="password">Mot de passe : </label>
                <input type="password" id="password" name="password" required>
            </div>
            <button type="submit" class="button">Connexion</button>
        </form>
        
                <?php 
                $getInfo = filter_input(INPUT_GET, "info",  FILTER_DEFAULT);
                if($getInfo == 'errorLogin'){
                    echo "<div>
                            <p>L'identifiant ou le mot de passe n'existe pas</p>
                        </div>";
                    }?>
            
    </div>

    <div class="column">
        <form action="" method ="POST">
            <h2>Inscription</h2>
            <div class="pseudo">
                <label for="pseudo">Pseudo : </label>
                <input type="text" id="pseudo" name="pseudo">
            </div>
            <div class="password">
                <label for="password">Mot de passe : </label>
                <input type="password" id="password" name="password">
            </div>
            <div class="confirmedPassword">
                <label for="password">Confirmation du mot de passe : </label>
                <input type="password" id="confirmedPassword" name="confirmedPassword">
            </div>
            <button type="submit">Inscription</button>
        </form>
    </div>
</div>